[project]
name = "handyr"
r_version = ">=4.1.0"
description = "Generally useful functions"

[dependencies]
dplyr = "*"
httr = "*"
lubridate = "*"
prettyunits = "*"
rlang = "*"
rvest = "*"
tidyr = "*"
DBI = "*"
RPostgres = "*"
RSQLite = "*"
dbplyr = "*"
duckdb = "*"
future = "*"
"future.apply" = "*"
ggplot2 = "*"
lutz = "*"
matrixStats = "*"
osmdata = "*"
pbapply = "*"
rappdirs = "*"
sf = "*"
testthat = ">=3.0.0"
tidygeocoder = "*"
units = "*"
withr = "*"
zoo = "*"
